# Generated by Django 3.1.3 on 2023-03-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0007_auto_20230302_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(),
        ),
    ]
